// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Ec850jlwyzMY7OG9gYN4sp3slDL0xvQ',
    appId: '1:507803724083:web:08d6df3c96d0e992873646',
    messagingSenderId: '507803724083',
    projectId: 'tweet-f87b5',
    authDomain: 'tweet-f87b5.firebaseapp.com',
    storageBucket: 'tweet-f87b5.appspot.com',
    measurementId: 'G-21V7V1VLEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YcIT7e6KqvFyzTTqmgJjvsDYlwURGuc',
    appId: '1:507803724083:android:45cd650bf54f9c23873646',
    messagingSenderId: '507803724083',
    projectId: 'tweet-f87b5',
    storageBucket: 'tweet-f87b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_gMgN3aqraqLDski46ZWrxFJ4KBps6w',
    appId: '1:507803724083:ios:639ba4828a05989f873646',
    messagingSenderId: '507803724083',
    projectId: 'tweet-f87b5',
    storageBucket: 'tweet-f87b5.appspot.com',
    iosBundleId: 'com.manocodes.tweet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_gMgN3aqraqLDski46ZWrxFJ4KBps6w',
    appId: '1:507803724083:ios:13cb1f18dd444624873646',
    messagingSenderId: '507803724083',
    projectId: 'tweet-f87b5',
    storageBucket: 'tweet-f87b5.appspot.com',
    iosBundleId: 'com.manocodes.tweet.RunnerTests',
  );
}
